// flow-typed signature: fc253600d1972efe70f6e524e39f41de
// flow-typed version: <<STUB>>/flow-node_v^1.2.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-node/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-node/index' {
  declare module.exports: $Exports<'flow-node'>;
}
declare module 'flow-node/index.js' {
  declare module.exports: $Exports<'flow-node'>;
}
declare module 'flow-node/register.js' {
  declare module.exports: $Exports<'flow-node/register'>;
}
