// flow-typed signature: 83f8482b81908ef87af89482761e763e
// flow-typed version: <<STUB>>/partial.lenses.validation_v^2.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'partial.lenses.validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'partial.lenses.validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'partial.lenses.validation/dist/partial.lenses.validation.cjs' {
  declare module.exports: any;
}

declare module 'partial.lenses.validation/dist/partial.lenses.validation.es' {
  declare module.exports: any;
}

declare module 'partial.lenses.validation/dist/partial.lenses.validation' {
  declare module.exports: any;
}

declare module 'partial.lenses.validation/dist/partial.lenses.validation.min' {
  declare module.exports: any;
}

declare module 'partial.lenses.validation/src/core' {
  declare module.exports: any;
}

declare module 'partial.lenses.validation/src/ext/infestines' {
  declare module.exports: any;
}

declare module 'partial.lenses.validation/src/partial.lenses.validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'partial.lenses.validation/dist/partial.lenses.validation.cjs.js' {
  declare module.exports: $Exports<'partial.lenses.validation/dist/partial.lenses.validation.cjs'>;
}
declare module 'partial.lenses.validation/dist/partial.lenses.validation.es.js' {
  declare module.exports: $Exports<'partial.lenses.validation/dist/partial.lenses.validation.es'>;
}
declare module 'partial.lenses.validation/dist/partial.lenses.validation.js' {
  declare module.exports: $Exports<'partial.lenses.validation/dist/partial.lenses.validation'>;
}
declare module 'partial.lenses.validation/dist/partial.lenses.validation.min.js' {
  declare module.exports: $Exports<'partial.lenses.validation/dist/partial.lenses.validation.min'>;
}
declare module 'partial.lenses.validation/src/core.js' {
  declare module.exports: $Exports<'partial.lenses.validation/src/core'>;
}
declare module 'partial.lenses.validation/src/ext/infestines.js' {
  declare module.exports: $Exports<'partial.lenses.validation/src/ext/infestines'>;
}
declare module 'partial.lenses.validation/src/partial.lenses.validation.js' {
  declare module.exports: $Exports<'partial.lenses.validation/src/partial.lenses.validation'>;
}
