// flow-typed signature: 05f6de777d36cd9adb37f365bf15aa7a
// flow-typed version: <<STUB>>/sanctuary-def_v^0.18.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanctuary-def'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanctuary-def' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sanctuary-def/index' {
  declare module.exports: $Exports<'sanctuary-def'>;
}
declare module 'sanctuary-def/index.js' {
  declare module.exports: $Exports<'sanctuary-def'>;
}
