// flow-typed signature: 30917b8e384a263474423faced824f96
// flow-typed version: <<STUB>>/sanctuary-type-classes_v^9.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanctuary-type-classes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanctuary-type-classes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sanctuary-type-classes/index' {
  declare module.exports: $Exports<'sanctuary-type-classes'>;
}
declare module 'sanctuary-type-classes/index.js' {
  declare module.exports: $Exports<'sanctuary-type-classes'>;
}
